{
 "title": "Dell Enterprise SONiC : Interface Rate (P)",
 "description": "Dell Enterprise SONiC : Interface Rate (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Sampling", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "switch",
    "label": "switch",
    "query": "label_values(ifcounters_counters_in_pkts, host)"
   },
   {
    "name": "netif",
    "label": "Network Interface",
    "query": "label_values(ifcounters_counters_in_pkts{host=\"$switch\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "$netif", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "netif" },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_info{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "Link MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_mtu_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "$netif : Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_in_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (bps)"
    },
    {
     "expr": "rate(ifcounters_out_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (bps)"
    }
   ]
  },
  {
   "title": "$netif : Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (pps)"
    },
    {
     "expr": "rate(ifcounters_counters_out_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (pps)"
    }
   ]
  },
  {
   "title": "$netif : Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_out_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_in_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (errors)"
    },
    {
     "expr": "rate(ifcounters_counters_out_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (errors)"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_network_speed_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"})*8)/1000000000"
    }
   ]
  },
  { "title": "$netif", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_info{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "Link MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_mtu_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "$netif : Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_in_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (bps)"
    },
    {
     "expr": "rate(ifcounters_out_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (bps)"
    }
   ]
  },
  {
   "title": "$netif : Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (pps)"
    },
    {
     "expr": "rate(ifcounters_counters_out_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (pps)"
    }
   ]
  },
  {
   "title": "$netif : Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_out_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_in_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (errors)"
    },
    {
     "expr": "rate(ifcounters_counters_out_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (errors)"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_network_speed_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"})*8)/1000000000"
    }
   ]
  },
  { "title": "$netif", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_info{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "Link MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_mtu_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "$netif : Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_in_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (bps)"
    },
    {
     "expr": "rate(ifcounters_out_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (bps)"
    }
   ]
  },
  {
   "title": "$netif : Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (pps)"
    },
    {
     "expr": "rate(ifcounters_counters_out_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (pps)"
    }
   ]
  },
  {
   "title": "$netif : Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_out_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_in_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (errors)"
    },
    {
     "expr": "rate(ifcounters_counters_out_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (errors)"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_network_speed_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"})*8)/1000000000"
    }
   ]
  },
  { "title": "$netif", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_info{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "Link MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_mtu_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "$netif : Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_in_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (bps)"
    },
    {
     "expr": "rate(ifcounters_out_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (bps)"
    }
   ]
  },
  {
   "title": "$netif : Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (pps)"
    },
    {
     "expr": "rate(ifcounters_counters_out_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (pps)"
    }
   ]
  },
  {
   "title": "$netif : Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_out_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_in_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (errors)"
    },
    {
     "expr": "rate(ifcounters_counters_out_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (errors)"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_network_speed_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"})*8)/1000000000"
    }
   ]
  },
  { "title": "$netif", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_info{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "Link MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_mtu_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "$netif : Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_in_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (bps)"
    },
    {
     "expr": "rate(ifcounters_out_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (bps)"
    }
   ]
  },
  {
   "title": "$netif : Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 33 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (pps)"
    },
    {
     "expr": "rate(ifcounters_counters_out_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (pps)"
    }
   ]
  },
  {
   "title": "$netif : Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_out_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_in_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (errors)"
    },
    {
     "expr": "rate(ifcounters_counters_out_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (errors)"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_network_speed_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"})*8)/1000000000"
    }
   ]
  },
  { "title": "$netif", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_info{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "Link MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_mtu_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "$netif : Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_in_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (bps)"
    },
    {
     "expr": "rate(ifcounters_out_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (bps)"
    }
   ]
  },
  {
   "title": "$netif : Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 41 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (pps)"
    },
    {
     "expr": "rate(ifcounters_counters_out_pkts{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (pps)"
    }
   ]
  },
  {
   "title": "$netif : Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifcounters_counters_in_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_out_discards{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (discards)"
    },
    {
     "expr": "rate(ifcounters_counters_in_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (errors)"
    },
    {
     "expr": "rate(ifcounters_counters_out_errors{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (errors)"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_network_speed_bytes{job=~\"[[switch]]_NE\",device=~\"[[netif]]\"})*8)/1000000000"
    }
   ]
  }
 ]
}